[project]
name = "repl-nix-surveydataanalyzer-1"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "plotly>=5.24.1",
    "reportlab>=4.2.5",
    "streamlit>=1.40.2",
]
